name: Resume Pre-Prod

on:
  pull_request:
    paths:
      - "resume.tex"

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Build PDF
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error resume.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-preview
          path: resume.pdf
